"use client";

// pages/index.js
import Head from "next/head";
import Stack from "@mui/material/Stack";
import { Gauge } from "@mui/x-charts/Gauge";
import { LineChart } from "@mui/x-charts/LineChart";
import { PieChart } from "@mui/x-charts/PieChart";

export default function Home() {
  return (
    <div className="bg-gray-900 min-h-screen text-white">
      <div>
        <div className="presentacion">
          <div className="titulo p-10">
            <h1 className=" font-bold text-2xl ">BTC/ETH portfolio</h1>
          </div>
          <div className="informacion p-10">
            {/* Aquí va el contenido de la presentación */}
            <p>
              Maximize your crypto returns with our innovative portfolio. We combine the top two cryptocurrencies with
              machine learning for optimal daily rebalancing.
            </p>
          </div>
        </div>
      </div>{" "}
      {/* Fondo oscuro y altura mínima de pantalla */}
      <Head>
        <title>Mi Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto p-4">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
          {/* Primera fila */}
          <div className="bg-gray-800 rounded-lg shadow p-4 col-span-3">
            <h1 className="font-bold text-ellipsis">Historical returns</h1>
            <LineChart
              xAxis={[{ data: [1, 2, 3, 5, 8, 10] }]}
              series={[
                {
                  data: [2, 5.5, 2, 8.5, 1.5, 5],
                },
              ]}
              width={500}
              height={300}
            />
          </div>
          <div className="bg-gray-800 rounded-lg shadow p-4  ">
            <h1>Summary</h1>
            <PieChart
              series={[
                {
                  data: [
                    { id: 0, value: 10, label: "series A" },
                    { id: 1, value: 15, label: "series B" },
                    { id: 2, value: 20, label: "series C" },
                  ],
                },
              ]}
              width={400}
              height={200}
            />
          </div>

          {/* Segunda fila */}
          <div className="bg-gray-800 rounded-lg shadow p-4">
            <div className="stats shadow">
              <div className="stat">
                <div className="stat-figure text-primary">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="24"
                    height="24"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    className="feather feather-check"
                  >
                    <polyline points="20 6 9 17 4 12"></polyline>
                  </svg>
                </div>
                <div className="stat-title">risk aversion</div>
                <div className="stat-value text-primary"></div>
                <div className="stat-desc">21% more than last month</div>

                <div className="rating">
                  <input type="radio" name="rating-1" className="mask mask-star" />
                  <input type="radio" name="rating-1" className="mask mask-star" defaultChecked />
                  <input type="radio" name="rating-1" className="mask mask-star" />
                  <input type="radio" name="rating-1" className="mask mask-star" />
                  <input type="radio" name="rating-1" className="mask mask-star" />
                </div>
              </div>
            </div>
          </div>

          <div className="bg-gray-800 rounded-lg shadow p-4">
            <Stack direction={{ xs: "column", md: "row" }} spacing={{ xs: 1, md: 3 }}>
              <Gauge width={100} height={100} value={60} />
              <Gauge width={100} height={100} value={60} startAngle={-90} endAngle={90} />
            </Stack>
          </div>
          <div className="bg-gray-800 rounded-lg shadow p-4 col-span-2 ">
            <ul className="menu bg-base-200 rounded-box w-56">
              <li>
                <a>Item 1</a>
              </li>
              <li>
                <a>Item 2</a>
              </li>
              <li>
                <a>Item 3</a>
              </li>
            </ul>
          </div>
        </div>
      </main>
    </div>
  );
}
