"use client";

import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Stack from "@mui/material/Stack";
import { Gauge } from "@mui/x-charts/Gauge";
import { PieChart } from "@mui/x-charts/PieChart";
import { EtherInput } from "~~/components/scaffold-eth";

export default function Home() {
  const [ethAmount, setEthAmount] = useState("");

  return (
    <div className="min-h-screen bg-white dark:bg-gray-900 text-black dark:text-white">
      <div>
        <div className="presentacion p-4">
          <div className="titulo">
            <h1 className="font-bold text-4xl ">BTC/ETH portfolio</h1>
          </div>
          <div className="informacion">
            <p>
              Maximize your crypto returns with our innovative portfolio. We combine the top two cryptocurrencies with
              machine learning for optimal daily rebalancing.
            </p>
            <div>Enter amount</div>
            <EtherInput value={ethAmount} onChange={amount => setEthAmount(amount)} />
          </div>
          <a href="/debug">
            <button className="btn btn-lg sm:btn-sm md:btn-md lg:btn-lg bg-slate-400 dark:bg-slate-600 justify-end p-4">
              BUY NOW
            </button>
          </a>
        </div>
      </div>

      <Head>
        <title>Mi Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto p-4">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
          {/* Primera fila */}
          <div className="bg-gray-800 dark:bg-gray-700 rounded-lg shadow p-4 col-span-3">
            <h1 className="font-bold text-ellipsis">Historical returns</h1>
            <Image className=" mt-10" src="/i-7.png" alt="Shoes" width={1400} height={800} />
          </div>
          <div className="bg-gray-800 dark:bg-gray-700 rounded-lg shadow p-4">
            <div>
              <h1>Portfolio´s performance</h1>
            </div>
            <ul className="menu bg-base-200 dark:bg-gray-600 rounded-box w-56">
              <li>
                <a>Market Risk Premium: 0.8796147246970394</a>
              </li>
              <li>
                <a>Market Risk Premium: 0.8796147246970394</a>
              </li>
              <li>
                <a>Market Risk Premium: 0.8796147246970394</a>
              </li>
              <li>
                <a>Market Risk Premium: 0.8796147246970394</a>
              </li>
              <li>
                <a>Market Risk Premium: 0.8796147246970394</a>
              </li>
              <li>
                <a>Market Risk Premium: 0.8796147246970394</a>
              </li>
              {/* ... other list items ... */}
            </ul>
          </div>

          {/* Segunda fila */}
          <div className="bg-gray-800 dark:bg-gray-700 rounded-lg shadow p-4">
            <div className="stats shadow">
              <div className="stat">
                <div className="stat-figure text-primary">{/* ... SVG icon ... */}</div>

                <div className="stat-title">risk aversion</div>
                <div className="stat-value text-primary"></div>
                <div className="stat-desc">21% more than last month</div>

                <div className="rating">{/* ... rating stars ... */}</div>
              </div>
            </div>
          </div>

          <div className="bg-gray-800 dark:bg-gray-700 rounded-lg shadow p-4">
            <h1>Vote governance!</h1>
            <Stack direction={{ xs: "column", md: "row" }} spacing={{ xs: 1, md: 3 }}>
              <Gauge width={100} height={100} value={60} />

              <Gauge width={100} height={100} value={60} startAngle={-90} endAngle={90} />
            </Stack>
            <p>ETHER</p> <p>BTC</p>
          </div>

          <div className="bg-gray-800 dark:bg-gray-700 rounded-lg shadow p-4 col-span-2">
            <h1>Summary</h1>
            <PieChart
              series={[
                {
                  data: [
                    { id: 1, value: 15, label: "BITCOIN" },
                    { id: 2, value: 20, label: "ETHEREUM" },
                  ],
                },
              ]}
              width={400}
              height={200}
            />
          </div>
        </div>
      </main>
    </div>
  );
}
