// pages/index.js
import Head from "next/head";

export default function Home() {
  return (
    <div className="bg-gray-900 min-h-screen text-white">
      <div>
        <div className="presentacion">
          <div className="titulo p-10">
            <h1 className=" font-bold text-2xl ">BTC/ETH portfolio</h1>
          </div>
          <div className="informacion p-10">
            {/* Aquí va el contenido de la presentación */}
            <p>
              Maximize your crypto returns with our innovative portfolio. We combine the top two cryptocurrencies with
              machine learning for optimal daily rebalancing.
            </p>
          </div>
        </div>
      </div>{" "}
      {/* Fondo oscuro y altura mínima de pantalla */}
      <Head>
        <title>Mi Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto p-4">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
          {/* Primera fila */}
          <div className="bg-gray-800 rounded-lg shadow p-4 col-span-3"></div>
          <div className="bg-gray-800 rounded-lg shadow p-4 ">
            <h1>Summary</h1>
            <div className="grid grid-cols-2">
              <div
                className="radial-progress"
                style={{ "--value": "70", "--size": "12rem", "--thickness": "2px" }}
                role="progressbar"
              >
                70%
              </div>
              <div className="p-20">
                <p>BTC</p>
                <p>ETH</p>
              </div>
            </div>
          </div>

          {/* Segunda fila */}
          <div className="bg-gray-800 rounded-lg shadow p-4">
            <div className="stats shadow">
              <div className="stat">
                <div className="stat-figure text-primary">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    className="inline-block h-8 w-8 stroke-current"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                      d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z"
                    ></path>
                  </svg>
                </div>
                <div className="stat-title">Total Likes</div>
                <div className="stat-value text-primary">25.6K</div>
                <div className="stat-desc">21% more than last month</div>

                <div className="rating">
                  <input type="radio" name="rating-1" className="mask mask-star" />
                  <input type="radio" name="rating-1" className="mask mask-star" defaultChecked />
                  <input type="radio" name="rating-1" className="mask mask-star" />
                  <input type="radio" name="rating-1" className="mask mask-star" />
                  <input type="radio" name="rating-1" className="mask mask-star" />
                </div>
              </div>
            </div>
          </div>
          <div className="bg-gray-800 rounded-lg shadow p-4"></div>
          <div className="bg-gray-800 rounded-lg shadow p-4 col-span-2 items-center justify-center"></div>
        </div>
      </main>
    </div>
  );
}
